from enum import StrEnum


class AssignmentStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"


class RequirementType(StrEnum):
    FUNCTIONAL = "FUNCTIONAL"
    TECHNICAL = "TECHNICAL"
    DESIGN = "DESIGN"
    DOCUMENTATION = "DOCUMENTATION"
    CONSTRAINT = "CONSTRAINT"
    OTHER = "OTHER"


class RequirementPriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class WorkspaceRole(StrEnum):
    OWNER = "OWNER"
    MEMBER = "MEMBER"


class NotificationType(StrEnum):
    INFO = "INFO"
    DEADLINE = "DEADLINE"
    SYSTEM = "SYSTEM"


class AuditEventType(StrEnum):
    USER_REGISTERED = "USER_REGISTERED"
    ASSIGNMENT_CREATED = "ASSIGNMENT_CREATED"
    ASSIGNMENT_UPDATED = "ASSIGNMENT_UPDATED"
    ASSIGNMENT_DELETED = "ASSIGNMENT_DELETED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_DELETED = "DOCUMENT_DELETED"
    COURSE_CREATED = "COURSE_CREATED"
    COURSE_UPDATED = "COURSE_UPDATED"
    COURSE_DELETED = "COURSE_DELETED"
