from enum import StrEnum


class AssignmentStatus(StrEnum):
    """Lifecycle of an assignment specification.

    Phase 2 splits Phase 1's ``ACTIVE`` into the explicit readiness states
    ``INCOMPLETE`` and ``READY_FOR_ANALYSIS``. ``ACTIVE`` is kept as a
    deprecated alias so Phase 1 clients and rows keep working; nothing in the
    application produces it any more.
    """

    DRAFT = "DRAFT"
    INCOMPLETE = "INCOMPLETE"
    READY_FOR_ANALYSIS = "READY_FOR_ANALYSIS"
    ANALYSIS_IN_PROGRESS = "ANALYSIS_IN_PROGRESS"
    ANALYZED = "ANALYZED"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"
    ACTIVE = "ACTIVE"


class RequirementStatus(StrEnum):
    """Progress of one requirement. Independent from ``AssignmentStatus``."""

    TODO = "TODO"
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    VERIFIED = "VERIFIED"


class RequirementType(StrEnum):
    FUNCTIONAL = "FUNCTIONAL"
    TECHNICAL = "TECHICAL"
    DESIGN = "DESIGN"
    DOCUMENTATION = "DOCUMENTATION"
    CONSTRAINT = "CONSTRAINT"
    PERFORMANCE = "PERFORMANCE"
    SECURITY = "SECURITY"
    TESTING = "TESTING"
    OTHER = "OTHER"


class RequirementPriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ConstraintType(StrEnum):
    TECHNOLOGY = "TECHNOLOGY"
    TIME = "TIME"
    RESOURCE = "RESOURCE"
    FORMAT = "FORMAT"
    LANGUAGE = "LANGUAGE"
    LIBRARY = "LIBRARY"
    PLATFORM = "PLATFORM"
    ACADEMIC = "ACADEMIC"
    SECURITY = "SECURITY"
    PERFORMANCE = "PERFORMANCE"
    OTHER = "OTHER"


class ConstraintSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    IMPORTANT = "IMPORTANT"
    CRITICAL = "CRITICAL"


class DeliverableType(StrEnum):
    SOURCE_CODE = "SOURCE_CODE"
    DOCUMENT = "DOCUMENT"
    DATASET = "DATASET"
    PRESENTATION = "PRESENTATION"
    TEST_SUITE = "TEST_SUITE"
    VIDEO = "VIDEO"
    OTHER = "OTHER"


class DeliverableStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    VERIFIED = "VERIFIED"


class TechnologyCategory(StrEnum):
    LANGUAGE = "LANGUAGE"
    FRAMEWORK = "FRAMEWORK"
    DATABASE = "DATABASE"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    LIBRARY = "LIBRARY"
    TOOL = "TOOL"
    PROTOCOL = "PROTOCOL"
    OTHER = "OTHER"


class CompletenessCheckStatus(StrEnum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"


class WorkspaceRole(StrEnum):
    OWNER = "OWNER"
    MEMBER = "MEMBER"


class NotificationType(StrEnum):
    INFO = "INFO"
    DEADLINE = "DEADLINE"
    SYSTEM = "SYSTEM"


class AuditEventType(StrEnum):
    USER_REGISTERED = "USER_REGISTERED"
    ASSIGNMENT_CREATED = "ASSIGNMENT_CREATED"
    ASSIGNMENT_UPDATED = "ASSIGNMENT_UPDATED"
    ASSIGNMENT_DELETED = "ASSIGNMENT_DELETED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_DELETED = "DOCUMENT_DELETED"
    COURSE_CREATED = "COURSE_CREATED"
    COURSE_UPDATED = "COURSE_UPDATED"
    COURSE_DELETED = "COURSE_DELETED"
    REQUIREMENT_CREATED = "REQUIREMENT_CREATED"
    REQUIREMENT_UPDATED = "REQUIREMENT_UPDATED"
    REQUIREMENT_DELETED = "REQUIREMENT_DELETED"
    REQUIREMENT_COMPLETED = "REQUIREMENT_COMPLETED"
    CONSTRAINT_CREATED = "CONSTRAINT_CREATED"
    CONSTRAINT_UPDATED = "CONSTRAINT_UPDATED"
    CONSTRAINT_DELETED = "CONSTRAINT_DELETED"
    CRITERION_CREATED = "CRITERION_CREATED"
    CRITERION_UPDATED = "CRITERION_UPDATED"
    CRITERION_DELETED = "CRITERION_DELETED"
    DELIVERABLE_CREATED = "DELIVERABLE_CREATED"
    DELIVERABLE_UPDATED = "DELIVERABLE_UPDATED"
    DELIVERABLE_DELETED = "DELIVERABLE_DELETED"
    TECHNOLOGY_ADDED = "TECHNOLOGY_ADDED"
    TECHNOLOGY_REMOVED = "TECHNOLOGY_REMOVED"
    TAG_ADDED = "TAG_ADDED"
    TAG_REMOVED = "TAG_REMOVED"
    SPECIFICATION_VALIDATED = "SPECIFICATION_VALIDATED"
    SPECIFICATION_MARKED_READY = "SPECIFICATION_MARKED_READY"
    SPECIFICATION_INVALIDATED = "SPECIFICATION_INVALIDATED"
    SPECIFICATION_VERSION_CREATED = "SPECIFICATION_VERSION_CREATED"
