"""Domain lexicons for deterministic academic analysis.

These keyword rules let the mock provider classify and analyze assignments
without any model call and without any network access, which is what makes the
test suite and CI reproducible. They are deliberately broad and domain-agnostic:
programming is one lexicon among many, never the default.

The lexicon is also the reference vocabulary the specialized analyzers use when
they need to detect, for example, a proof requirement in free text.
"""

from __future__ import annotations

from app.models.enums import AcademicDomain, AssignmentType, RequirementCategory

#: Keyword -> assignment type. Matching is case-insensitive on word boundaries
#: where possible; multi-word phrases are matched as substrings.
TYPE_KEYWORDS: dict[AssignmentType, tuple[str, ...]] = {
    AssignmentType.MATHEMATICAL_PROOF: (
        "prove",
        "proof",
        "theorem",
        "lemma",
        "corollary",
        "q.e.d",
        "qed",
        "show that",
        "derive rigorously",
        "induction",
        "contradiction",
        "deduce",
    ),
    AssignmentType.PROBLEM_SET: (
        "problem set",
        "problems",
        "exercise",
        "exercises",
        "solve",
        "compute",
        "calculate",
        "worksheet",
        "questions 1",
        "homework",
    ),
    AssignmentType.PROGRAMMING: (
        "program",
        "implement",
        "source code",
        "compile",
        "algorithm",
        "function",
        "class",
        "script",
        "unit test",
        "repository",
        "bug",
        "software",
        "api",
        "code",
    ),
    AssignmentType.DATA_ANALYSIS: (
        "dataset",
        "data analysis",
        "analyze the data",
        "regression",
        "statistical",
        "statistics",
        "correlation",
        "visualization",
        "visualisation",
        "clean the data",
        "pandas",
        "hypothesis test",
    ),
    AssignmentType.LAB_REPORT: (
        "lab report",
        "laboratory",
        "experiment",
        "procedure",
        "measurement",
        "measurements",
        "apparatus",
        "error analysis",
        "titration",
        "observation",
        "specimen",
    ),
    AssignmentType.RESEARCH: (
        "research paper",
        "research question",
        "literature",
        "sources",
        "cite",
        "citation",
        "methodology",
        "argument",
        "findings",
        "abstract",
        "peer-reviewed",
        "journal",
    ),
    AssignmentType.LITERATURE_REVIEW: (
        "literature review",
        "review of the literature",
        "survey the literature",
        "systematic review",
        "compare sources",
        "synthesize sources",
    ),
    AssignmentType.ESSAY: (
        "essay",
        "thesis statement",
        "argumentative",
        "write an essay",
        "paragraph",
        "introduction and conclusion",
        "word limit",
        "words",
    ),
    AssignmentType.PRESENTATION: (
        "presentation",
        "present",
        "slides",
        "slide deck",
        "powerpoint",
        "oral",
        "audience",
        "speak",
        "talk",
        "poster",
    ),
    AssignmentType.READING: (
        "reading",
        "read the",
        "chapter",
        "annotation",
        "annotate",
        "summary of the reading",
        "response paper",
    ),
    AssignmentType.LANGUAGE: (
        "translation",
        "translate",
        "grammar",
        "vocabulary",
        "conjugate",
        "comprehension",
        "dialogue",
        "pronunciation",
        "language",
    ),
    AssignmentType.DESIGN: (
        "design",
        "prototype",
        "wireframe",
        "mockup",
        "sketch",
        "portfolio",
        "visual",
        "user experience",
        "ux",
        "artifact",
    ),
    AssignmentType.GROUP_PROJECT: (
        "group project",
        "group",
        "team",
        "collaborate",
        "collaboration",
        "teammates",
        "members",
        "peer review",
    ),
    AssignmentType.REPORT: (
        "report",
        "write a report",
        "technical report",
        "business report",
        "memo",
    ),
}

#: Keyword -> academic domain.
DOMAIN_KEYWORDS: dict[AcademicDomain, tuple[str, ...]] = {
    AcademicDomain.MATHEMATICS: (
        "math",
        "mathematics",
        "theorem",
        "proof",
        "algebra",
        "calculus",
        "geometry",
        "topology",
        "convergence",
        "integral",
        "derivative",
        "matrix",
        "linear algebra",
        "probability",
    ),
    AcademicDomain.COMPUTER_SCIENCE: (
        "computer science",
        "algorithm",
        "software",
        "programming",
        "data structure",
        "machine learning",
        "database",
        "operating system",
        "network",
        "compiler",
        "complexity",
    ),
    AcademicDomain.PHYSICS: (
        "physics",
        "mechanic",
        "quantum",
        "thermodynamic",
        "electromagnetic",
        "optics",
        "velocity",
        "newton",
        "relativity",
        "momentum",
    ),
    AcademicDomain.CHEMISTRY: (
        "chemistry",
        "chemical",
        "molecule",
        "reaction",
        "titration",
        "compound",
        "organic",
        "inorganic",
        "molar",
        "acid",
    ),
    AcademicDomain.BIOLOGY: (
        "biology",
        "cell",
        "dna",
        "organism",
        "genetic",
        "ecology",
        "species",
        "protein",
        "evolution",
        "microbiology",
    ),
    AcademicDomain.ENGINEERING: (
        "engineering",
        "circuit",
        "mechanical",
        "structural",
        "tolerance",
        "manufacturing",
        "robot",
        "thermodynamic cycle",
        "civil",
        "electrical",
    ),
    AcademicDomain.ECONOMICS: (
        "economics",
        "economic",
        "market",
        "supply and demand",
        "inflation",
        "gdp",
        "macroeconomics",
        "microeconomics",
        "fiscal",
        "finance",
        "labour",
        "labor",
    ),
    AcademicDomain.BUSINESS: (
        "business",
        "marketing",
        "management",
        "strategy",
        "stakeholder",
        "financial statement",
        "case study",
        "entrepreneur",
        "operations",
    ),
    AcademicDomain.SOCIAL_SCIENCES: (
        "sociology",
        "psychology",
        "anthropology",
        "political science",
        "social",
        "survey",
        "qualitative",
        "ethnograph",
        "policy",
        "education",
        "student performance",
        "learning",
        "schooling",
    ),
    AcademicDomain.HUMANITIES: (
        "history",
        "philosophy",
        "literature",
        "literary",
        "ethics",
        "religion",
        "philosophical",
        "historical",
        "textual",
    ),
    AcademicDomain.LANGUAGES: (
        "language",
        "translation",
        "grammar",
        "spanish",
        "french",
        "german",
        "mandarin",
        "vocabulary",
        "linguistic",
    ),
    AcademicDomain.ART_AND_DESIGN: (
        "art",
        "painting",
        "sculpture",
        "graphic design",
        "portfolio",
        "aesthetic",
        "illustration",
        "typography",
    ),
}

#: Vague phrasing that usually hides a real requirement. Flagged as ambiguity
#: instead of being invented into a definition.
VAGUE_PHRASES: tuple[str, ...] = (
    "appropriate sources",
    "appropriate references",
    "relevant literature",
    "detailed analysis",
    "in-depth",
    "in depth",
    "sufficient detail",
    "good",
    "high quality",
    "interesting",
    "reasonable",
    "etc.",
    "and so on",
    "several",
    "some",
    "a few",
    "properly",
    "as needed",
    "as appropriate",
    "clear and concise",
)

#: Work-area templates per assignment type. Phase 4 turns these into tasks; they
#: are intentionally high level and academic, not executable steps.
WORK_AREA_TEMPLATES: dict[AssignmentType, tuple[tuple[str, RequirementCategory], ...]] = {
    AssignmentType.MATHEMATICAL_PROOF: (
        ("Review definitions and assumptions", RequirementCategory.CONTENT),
        ("Identify applicable theorems", RequirementCategory.METHODOLOGY),
        ("Construct the proof", RequirementCategory.CONTENT),
        ("Verify logical validity", RequirementCategory.QUALITY),
        ("Format the final solution", RequirementCategory.FORMAT),
    ),
    AssignmentType.PROBLEM_SET: (
        ("Review the relevant theory", RequirementCategory.CONTENT),
        ("Solve each problem", RequirementCategory.CONTENT),
        ("Check calculations", RequirementCategory.QUALITY),
        ("Write up worked solutions", RequirementCategory.DELIVERABLE),
    ),
    AssignmentType.PROGRAMMING: (
        ("Understand the requirements", RequirementCategory.PROCESS),
        ("Design the solution", RequirementCategory.METHODOLOGY),
        ("Implement the solution", RequirementCategory.TECHNICAL),
        ("Test the implementation", RequirementCategory.QUALITY),
        ("Document the work", RequirementCategory.DELIVERABLE),
    ),
    AssignmentType.DATA_ANALYSIS: (
        ("Obtain and inspect the dataset", RequirementCategory.PROCESS),
        ("Clean and transform the data", RequirementCategory.METHODOLOGY),
        ("Run the analysis", RequirementCategory.CONTENT),
        ("Create visualizations", RequirementCategory.PRESENTATION),
        ("Write up findings", RequirementCategory.DELIVERABLE),
    ),
    AssignmentType.LAB_REPORT: (
        ("Prepare the experiment", RequirementCategory.PROCESS),
        ("Run the experiment and collect data", RequirementCategory.METHODOLOGY),
        ("Process the measurements", RequirementCategory.CONTENT),
        ("Analyze sources of error", RequirementCategory.QUALITY),
        ("Write the lab report", RequirementCategory.DELIVERABLE),
    ),
    AssignmentType.RESEARCH: (
        ("Refine the research question", RequirementCategory.PROCESS),
        ("Search the literature", RequirementCategory.METHODOLOGY),
        ("Evaluate sources", RequirementCategory.QUALITY),
        ("Construct the argument", RequirementCategory.CONTENT),
        ("Write the paper", RequirementCategory.DELIVERABLE),
        ("Manage citations", RequirementCategory.ACADEMIC),
        ("Revise and proofread", RequirementCategory.QUALITY),
    ),
    AssignmentType.LITERATURE_REVIEW: (
        ("Define the review scope", RequirementCategory.PROCESS),
        ("Collect sources", RequirementCategory.METHODOLOGY),
        ("Synthesize and compare sources", RequirementCategory.CONTENT),
        ("Identify gaps and themes", RequirementCategory.CONTENT),
        ("Write the review", RequirementCategory.DELIVERABLE),
    ),
    AssignmentType.ESSAY: (
        ("Develop a thesis", RequirementCategory.PROCESS),
        ("Plan the structure", RequirementCategory.METHODOLOGY),
        ("Gather supporting evidence", RequirementCategory.CONTENT),
        ("Draft the essay", RequirementCategory.DELIVERABLE),
        ("Revise and proofread", RequirementCategory.QUALITY),
    ),
    AssignmentType.PRESENTATION: (
        ("Clarify the audience and message", RequirementCategory.PROCESS),
        ("Outline the presentation", RequirementCategory.METHODOLOGY),
        ("Build the slides", RequirementCategory.PRESENTATION),
        ("Rehearse the delivery", RequirementCategory.QUALITY),
    ),
    AssignmentType.READING: (
        ("Read the assigned material", RequirementCategory.CONTENT),
        ("Take structured notes", RequirementCategory.METHODOLOGY),
        ("Summarize the key ideas", RequirementCategory.DELIVERABLE),
    ),
    AssignmentType.LANGUAGE: (
        ("Review vocabulary and grammar", RequirementCategory.CONTENT),
        ("Complete the exercises or translation", RequirementCategory.CONTENT),
        ("Check accuracy and usage", RequirementCategory.QUALITY),
    ),
    AssignmentType.DESIGN: (
        ("Research the brief", RequirementCategory.PROCESS),
        ("Develop concepts", RequirementCategory.METHODOLOGY),
        ("Produce the design artifact", RequirementCategory.DELIVERABLE),
        ("Reflect and iterate", RequirementCategory.QUALITY),
    ),
    AssignmentType.GROUP_PROJECT: (
        ("Agree roles and plan", RequirementCategory.PROCESS),
        ("Complete individual contributions", RequirementCategory.CONTENT),
        ("Integrate the work", RequirementCategory.METHODOLOGY),
        ("Review together", RequirementCategory.QUALITY),
    ),
    AssignmentType.REPORT: (
        ("Gather the required information", RequirementCategory.CONTENT),
        ("Structure the report", RequirementCategory.METHODOLOGY),
        ("Write the report", RequirementCategory.DELIVERABLE),
        ("Review and finalize", RequirementCategory.QUALITY),
    ),
    AssignmentType.OTHER: (
        ("Understand the requirements", RequirementCategory.PROCESS),
        ("Do the academic work", RequirementCategory.CONTENT),
        ("Prepare the submission", RequirementCategory.DELIVERABLE),
    ),
}

#: How completion could later be verified, per assignment type. Each entry is
#: ``(title, description, method)`` where method is a generic verification kind.
VERIFICATION_TEMPLATES: dict[AssignmentType, tuple[tuple[str, str, str], ...]] = {
    AssignmentType.MATHEMATICAL_PROOF: (
        ("Proof completeness", "Every case and boundary condition is covered.", "PROOF_CHECK"),
        (
            "Logical validity",
            "Each step follows from definitions and cited theorems.",
            "PROOF_CHECK",
        ),
        (
            "Correct use of definitions",
            "Definitions and assumptions are applied exactly as stated.",
            "DEFINITION_CHECK",
        ),
    ),
    AssignmentType.PROBLEM_SET: (
        ("All problems attempted", "Every problem has a worked solution.", "COVERAGE_CHECK"),
        ("Calculation check", "Each numeric result is reproducible.", "CALCULATION_CHECK"),
        ("Method check", "The chosen method suits each problem.", "METHOD_CHECK"),
    ),
    AssignmentType.PROGRAMMING: (
        ("Build success", "The project compiles or runs from a clean checkout.", "BUILD_CHECK"),
        ("Tests", "Automated tests cover the required behaviour.", "CODE_TEST"),
        (
            "Requirement coverage",
            "Each requirement maps to implemented behaviour.",
            "COVERAGE_CHECK",
        ),
    ),
    AssignmentType.DATA_ANALYSIS: (
        (
            "Reproducibility",
            "The analysis runs end to end from the raw data.",
            "REPRODUCIBILITY_CHECK",
        ),
        ("Statistical validity", "Chosen methods suit the data and question.", "METHOD_CHECK"),
        ("Visualization accuracy", "Charts match the underlying data.", "DATA_CHECK"),
    ),
    AssignmentType.LAB_REPORT: (
        ("Measurements present", "Every required measurement is reported.", "COVERAGE_CHECK"),
        (
            "Calculations reproducible",
            "Derived values follow from the measurements.",
            "CALCULATION_CHECK",
        ),
        (
            "Error analysis included",
            "Sources of error are identified and discussed.",
            "QUALITY_CHECK",
        ),
    ),
    AssignmentType.RESEARCH: (
        ("Citation completeness", "Every claim that needs a source has one.", "CITATION_CHECK"),
        ("Source quality", "Sources meet the expected scholarly standard.", "SOURCE_QUALITY_CHECK"),
        (
            "Argument-evidence consistency",
            "Conclusions are supported by the presented evidence.",
            "ARGUMENT_CHECK",
        ),
    ),
    AssignmentType.LITERATURE_REVIEW: (
        ("Coverage", "The review covers the required body of work.", "COVERAGE_CHECK"),
        ("Synthesis", "Sources are compared and integrated, not listed.", "ARGUMENT_CHECK"),
        ("Citation completeness", "All referenced work is cited correctly.", "CITATION_CHECK"),
    ),
    AssignmentType.ESSAY: (
        ("Thesis clarity", "A clear, arguable thesis is present.", "ARGUMENT_CHECK"),
        ("Structure", "Paragraphs and sections support the thesis.", "STRUCTURE_CHECK"),
        ("Citation completeness", "Evidence is referenced where required.", "CITATION_CHECK"),
    ),
    AssignmentType.PRESENTATION: (
        ("Topic coverage", "All required topics appear.", "COVERAGE_CHECK"),
        ("Time limit", "The delivery fits the stated duration.", "TIME_CHECK"),
        ("Slide consistency", "Slides match the assignment and the talk.", "CONSISTENCY_CHECK"),
    ),
    AssignmentType.READING: (
        ("Coverage", "The assigned material is addressed.", "COVERAGE_CHECK"),
        ("Comprehension", "Key ideas are accurately summarized.", "QUALITY_CHECK"),
    ),
    AssignmentType.LANGUAGE: (
        ("Accuracy", "Grammar, spelling and usage are correct.", "QUALITY_CHECK"),
        ("Coverage", "All required exercises are completed.", "COVERAGE_CHECK"),
    ),
    AssignmentType.DESIGN: (
        ("Brief coverage", "The design addresses the stated brief.", "COVERAGE_CHECK"),
        ("Craft and consistency", "The artifact is coherent and intentional.", "QUALITY_CHECK"),
    ),
    AssignmentType.GROUP_PROJECT: (
        ("Contribution coverage", "All required parts are present.", "COVERAGE_CHECK"),
        ("Integration", "The parts form a coherent whole.", "CONSISTENCY_CHECK"),
    ),
    AssignmentType.REPORT: (
        ("Section coverage", "Every required section is present.", "COVERAGE_CHECK"),
        ("Requirement coverage", "Each requirement is addressed.", "COVERAGE_CHECK"),
        ("Internal consistency", "Numbers and conclusions agree.", "CONSISTENCY_CHECK"),
    ),
    AssignmentType.OTHER: (
        ("Requirement coverage", "Every requirement is addressed.", "COVERAGE_CHECK"),
        ("Quality", "The work meets the stated expectations.", "QUALITY_CHECK"),
    ),
}

#: Extension/mime hint -> coarse resource type. Resources are not assumed to be
#: academic prose: datasets, slides, code and images are all first-class.
RESOURCE_TYPE_BY_EXTENSION: dict[str, str] = {
    ".pdf": "PDF",
    ".docx": "DOCX",
    ".doc": "DOCX",
    ".txt": "TXT",
    ".md": "MD",
    ".markdown": "MD",
    ".pptx": "PPTX",
    ".ppt": "PPTX",
    ".csv": "CSV",
    ".xlsx": "XLSX",
    ".xls": "XLSX",
    ".png": "IMAGE",
    ".jpg": "IMAGE",
    ".jpeg": "IMAGE",
    ".gif": "IMAGE",
    ".svg": "IMAGE",
    ".py": "CODE",
    ".js": "CODE",
    ".ts": "CODE",
    ".java": "CODE",
    ".c": "CODE",
    ".cpp": "CODE",
    ".ipynb": "CODE",
    ".json": "DATA",
    ".zip": "ARCHIVE",
}

#: Filename/content hints -> the role a resource plays in the assignment.
RESOURCE_ROLE_HINTS: tuple[tuple[str, str], ...] = (
    ("rubric", "GRADING_RUBRIC"),
    ("grading", "GRADING_RUBRIC"),
    ("marking", "GRADING_RUBRIC"),
    ("slide", "LECTURE_SLIDES"),
    ("lecture", "LECTURE_SLIDES"),
    ("chapter", "TEXTBOOK_CHAPTER"),
    ("textbook", "TEXTBOOK_CHAPTER"),
    ("manual", "LAB_MANUAL"),
    ("lab", "LAB_MANUAL"),
    ("paper", "RESEARCH_PAPER"),
    ("journal", "RESEARCH_PAPER"),
    ("article", "RESEARCH_PAPER"),
    ("assignment", "ASSIGNMENT_BRIEF"),
    ("brief", "ASSIGNMENT_BRIEF"),
    ("instructions", "INSTRUCTOR_INSTRUCTIONS"),
    ("dataset", "DATASET"),
    ("data", "DATASET"),
    ("code", "CODE_FILE"),
    ("starter", "CODE_FILE"),
    ("skeleton", "CODE_FILE"),
    ("template", "TEMPLATE"),
)
